version: "3"

services:
  nginx:
   container_name: nginx
   image: nginx:latest
   ports:
    - "8888:80"
   volumes:
    - ./src:/src
    - ./default.conf:/etc/nginx/conf.d/default.conf
   links:
    - php
  php:
    container_name: php
    image: php:7-fpm
    volumes:
      - ./src:/src
      - ./env.php:/env.php
      - ./node_modules:/node_modules
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3308:3306"
    volumes:
      - ./db/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - my-datavolume:/var/lib/mysql
      - ./db/tables.sql:/docker-entrypoint-initdb.d/0_init.sql
volumes:
  my-datavolume:
