version: "3"

services:
  nginx:
   container_name: nginx
   image: nginx:latest
   ports:
    - "8080:80"
   volumes:
    - ./src:/src
    - ./default.conf:/etc/nginx/conf.d/default.conf
   links:
    - php
  php:
    container_name: php
    image: php:7-fpm
    volumes:
      - ./src:/src
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
