version: "3"

services:
  nginx:
   container_name: nginx
   image: nginx:latest
   ports:
    - "8080:80"
   volumes:
    - ./src:/src
    - ./default.conf:/etc/nginx/conf.d/default.conf
   links:
    - php
  php:
    container_name: php
    image: php:7-fpm
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - ./src:/src
    build:
      context: ./
  db:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3308:3306"