version: "3"

services:
  nginx:
   container_name: nginx
   image: nginx:latest
   ports:
    - "8080:80"
   volumes:
    - ./src:/src
    - ./default.conf:/etc/nginx/conf.d/default.conf
   links:
    - php
  php:
    container_name: php
    image: php:7-fpm
    volumes:
      - ./src:/src
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'test'
    ports:
      - "3308:3306"
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: