<?php
include_once getenv("VIEW_PATH") . 'common/header.phtml';

use \App\Models\Availability;
use \App\Models\Product;

$product = new Product();

if (isset($_GET['id']) && is_numeric($_GET['id'])) {
    $product->findById($_GET['id']);
}

$counter = 0;
$availabilities = Availability::getAllById($product->getId());
$categories = Product::getCategories();
$subcategories = Product::getSubcategories();
$categoriesAndSubcategories = Product::getCategoriesAndSubcategories();
?>

<div class="text-center">
    <img src="<?= '/image?product=' . $product->getImage() ?>" class="img-fluid" style="width: 500px" alt="Responsive image">
</div>

<form method="post" enctype="multipart/form-data">
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Are you sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger" formaction="<?= '/product/delete' ?>">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <input type="hidden" name="product[id]" value="<?= $product->getId() ?? '' ?>">

    <div class="form-row">
        <div class="form-group col-md-12">
            <div class="input-group-prepend">
                <label class="input-group-text" for="subcategoryInput">Name</label>
            </div>
            <input type="text" class="form-control" name="product[name]" value="<?= $product->getName() ?? '' ?>">
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="input-group-prepend">
                <label class="input-group-text" for="subcategoryInput">Brand</label>
            </div>
            <input type="text" class="form-control" name="product[brand]" value="<?= $product->getBrand() ?? '' ?>">
        </div>
        <div class="form-group col-md-6">
            <div class="input-group-prepend">
                <label class="input-group-text" for="subcategoryInput">Cost</label>
            </div>
            <input type="text" class="form-control" name="product[cost]" value="<?= $product->getCost() ?? '' ?>">
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="input-group-prepend">
                <label class="input-group-text" for="categoryInput">Category</label>
            </div>
            <select class="custom-select" id="category" name="product[category]" onchange="categoryChange()">
                <option>Choose...</option>
                <?php foreach ($categories as $key => $value) : ?>
                    <option value="<?= $value ?>"
                            <?php if (isset($product)) {
                                    echo $product->getCategory() == $value ? 'selected' : '';
                            }?>>
                    <?= $value ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group col-md-6">
            <div class="input-group-prepend">
                <label class="input-group-text" for="subcategoryInput">Subcategory</label>
            </div>
            <select class="custom-select subcategory-select" name="product[subcategory]">
                <option>Choose...</option>
                <?php foreach ($subcategories as $key => $value) : ?>
                    <option value="<?= $value ?>"
                        <?php if (isset($product)) {
                            echo $product->getSubcategory() == $value ? 'selected' : '';
                        }?>>
                        <?= $value ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="input-group-prepend">
                <label class="input-group-text" for="subcategoryInput">Image</label>
            </div>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="fileInput"
                       aria-describedby="inputGroupFileAddon01" name="image">
                <label class="custom-file-label" for="imageInput">Choose file</label>
            </div>
        </div>

        <div class="form-group col-md-6">
            <div class="input-group-prepend">
                <label class="input-group-text" for="targetGroupInput">Gender</label>
            </div>
            <select class="custom-select" name="product[target_group]">
                <?php foreach (Product::$targetGroupSelection as $group) : ?>
                    <option value="<?= $group ?>"
                        <?php if (isset($product)) {
                            echo $product->getTargetGroup() == $group ? 'selected' : '';
                        }?>>
                        <?= $group ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <?php if ($product->getId()): ?>
        <hr>
        <button type="button" class="btn btn-outline-primary mb-3" onclick="addRow(<?=$counter?>)" data-toggle="modal">Add</button>

        <div class="availabilities-wrapper">
            <?php foreach ($availabilities as $available) : ?>
                <input type="hidden" name="availability<?=$counter?>[product_id]" id="<?=$counter?>RowProductId" value="<?= $product->getId() ?>">

                <div class="input-group mb-3" id="<?=$counter?>Row">
                    <span class="input-group-text">Size</span>
                    <input type="number" class="form-control" name="availability<?=$counter?>[size]" value="<?= $available['size'] ?>">

                    <span class="input-group-text">Color</span>
                    <input type="text" class="form-control" name="availability<?=$counter?>[color]" value="<?= $available['color'] ?>">

                    <span class="input-group-text">Amount</span>
                    <input type="number" class="form-control" name="availability<?=$counter?>[amount]" value="<?= $available['amount'] ?>">

                    <span class="input-group-text">Sale</span>
                    <input type="number" step="0.01" class="form-control" name="availability<?=$counter?>[sale]" value="<?= $available['sale'] ?>">

                    <button type="button" class="btn btn-outline-danger" onclick="deleteRow(<?=$counter?>)" data-toggle="modal">X</button>
                </div>

                <input type="hidden" name="availability" id="<?=$counter?>RowAvailability" value="<?=$counter?>">
                <?php $counter++; ?>
            <?php endforeach; ?>
        </div>

        <hr>
    <?php endif; ?>

    <button type="submit" class="btn btn-primary" formaction="<?= '/product/update' ?>"><?php if ($product->getId()) { echo 'Update'; } else { echo 'Create'; } ?></button>
    <?php if ($product->getId()): ?>
        <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModalCenter">Delete</button>
    <?php endif; ?>
    <button type="submit" class="btn btn-warning float-right" formaction="<?= $_SERVER['HTTP_REFERER'] ?>">Back</button>
</form>

<script>
    var counter = <?=$counter?>;

    function categoryChange() {
        let e = document.getElementById("category");
        let category = e.options[e.selectedIndex].value;
        let subcategories = [];

        <?php foreach ($categoriesAndSubcategories as $key => $value) : ?>
            if (category === '<?=$value?>') {
                subcategories.push(['<?=$key?>']);
            }
        <?php endforeach; ?>

        insertOption(subcategories);
    }

    function insertOption(subcategories) {
        $('.subcategory-select')
            .find('option')
            .remove()
            .end()
            .append(
                '<option>Choose...</option>'
            );

        subcategories.forEach(function (item, index) {
            $('.subcategory-select').append(
                '<option value="' + item + '">' + item + '</option>'
            );
        });
    }

    function deleteRow(row) {
        $("#" + row + "RowProductId").remove();
        $("#" + row + "Row").remove();
        $("#" + row + "RowAvailability").remove();
    }

    function addRow() {
        $(".availabilities-wrapper").append(
            "<input type=\"hidden\" name=\"availability" + counter + "[product_id]\" id=\"" + counter + "RowProductId\" value=\"<?= $product->getId() ?>\">\n" +
            "<div class=\"input-group mb-3\" id=\"" + counter + "Row\"></div>\n" +
            "<input type=\"hidden\" name=\"availability\" value=\"" + counter + "\"  id=\"" + counter + "RowAvailability\">"
        );

        $("#" + counter + "Row").append(
            "<span class=\"input-group-text\">Size</span>\n" +
            "<input type=\"number\" class=\"form-control\" name=\"availability" + counter + "[size]\">\n" +
            "<span class=\"input-group-text\">Color</span>\n" +
            "<input type=\"text\" class=\"form-control\" name=\"availability" + counter + "[color]\">\n" +
            "<span class=\"input-group-text\">Amount</span>\n" +
            "<input type=\"number\" class=\"form-control\" name=\"availability" + counter + "[amount]\">\n" +
            "<span class=\"input-group-text\">Sale</span>\n" +
            "<input type=\"number\" step=\"0.01\" class=\"form-control\" name=\"availability" + counter + "[sale]\">\n" +
            "<button type=\"button\" class=\"btn btn-outline-danger\" onclick=\"deleteRow(" + counter + ")\" data-toggle=\"modal\">X</button>"
        );

        counter++;
    }

    $('#fileInput').on('change', function () {
        var fileName = $(this).val();
        $(this).next('.custom-file-label').html(fileName.replace('C:\\fakepath\\', " "));
    })
</script>

<?php
include_once getenv("VIEW_PATH") . 'common/footer.phtml';
?>
