<?php
include_once VIEW_PATH . 'common/header.phtml';

$product = new Product();

if (isset($_GET['id']) && is_numeric($_GET['id'])) {
    $product->findById($_GET['id']);
}

$counter = 0;
$availabilities = Availability::getAllAvailabilityById($product->getId());
$categories = Product::getCategories();
$subcategories = Product::getSubcategories();

?>

<div class="text-center">
    <img src="<?= '/image?product=' . $product->getImage() ?>" class="img-fluid" style="width: 500px" alt="Responsive image">
</div>

<form method="post" enctype="multipart/form-data">
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Are you sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger" formaction="<?= '/product/delete' ?>">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <input type="hidden" name="product[id]" value="<?= $product->getId() ?? '' ?>">

    <div class="form-row">
        <div class="form-group col-md-12">
            <div class="input-group-prepend">
                <label class="input-group-text" for="subcategoryInput">Name</label>
            </div>
            <input type="text" class="form-control" name="product[name]" value="<?= $product->getName() ?? '' ?>">
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="input-group-prepend">
                <label class="input-group-text" for="subcategoryInput">Brand</label>
            </div>
            <input type="text" class="form-control" name="product[brand]" value="<?= $product->getBrand() ?? '' ?>">
        </div>
        <div class="form-group col-md-6">
            <div class="input-group-prepend">
                <label class="input-group-text" for="subcategoryInput">Cost</label>
            </div>
            <input type="text" class="form-control" name="product[cost]" value="<?= $product->getCost() ?? '' ?>">
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="input-group-prepend">
                <label class="input-group-text" for="categoryInput">Category</label>
            </div>
            <select class="custom-select" id="category" name="product[category]" onchange="categoryChange()">
                <option>Choose...</option>
                <?php foreach ($categories as $key => $value) : ?>
                    <option value="<?= $value ?>"
                            <?php if (isset($product)) {
                                    echo $product->getCategory() == $value ? 'selected' : '';
                            }?>>
                    <?= $value ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group col-md-6">
            <div class="input-group-prepend">
                <label class="input-group-text" for="subcategoryInput">Subcategory</label>
            </div>
            <select class="custom-select" name="product[subcategory]">
                <option>Choose...</option>
                <?php foreach ($subcategories as $key => $value) : ?>
                    <option value="<?= $value ?>"
                        <?php if (isset($product)) {
                            echo $product->getSubcategory() == $value ? 'selected' : '';
                        }?>>
                        <?= $value ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-12">
            <div class="input-group-prepend">
                <label class="input-group-text" for="subcategoryInput">Image</label>
            </div>
            <div class="custom-file">
                <input type="file" class="custom-file-input"
                       aria-describedby="inputGroupFileAddon01" name="image">
                <label class="custom-file-label" for="imageInput">Choose file</label>
            </div>
        </div>
    </div>

    <hr>

    <?php foreach ($availabilities as $available) : ?>
        <input type="hidden" name="availability<?=$counter?>[product_id]" value="<?= $product->getId() ?>">

        <div class="input-group mb-3">
            <span class="input-group-text">Size</span>
            <input type="number" class="form-control" name="availability<?=$counter?>[size]" value="<?= $available['size'] ?>">

            <span class="input-group-text">Color</span>
            <input type="text" class="form-control" name="availability<?=$counter?>[color]" value="<?= $available['color'] ?>">

            <span class="input-group-text">Amount</span>
            <input type="number" class="form-control" name="availability<?=$counter?>[amount]" value="<?= $available['amount'] ?>">

            <span class="input-group-text">Sale</span>
            <input type="number" class="form-control" name="availability<?=$counter?>[sale]" value="<?= $available['sale'] ?>">
        </div>

        <input type="hidden" name="availability" value="<?=$counter?>">
        <?php $counter++; ?>
    <?php endforeach; ?>

    <button type="submit" class="btn btn-primary" formaction="<?= '/product/update' ?>"><?php if ($product->getId()) { echo 'Update'; } else { echo 'Create'; } ?></button>
    <?php if ($product->getId()): ?>
        <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModalCenter">Delete</button>
    <?php endif; ?>
    <button type="submit" class="btn btn-warning float-right" formaction="<?= '/admin/products' ?>">Back</button>
</form>

<script>
    categoryChange();

    function categoryChange() {
        var e = document.getElementById("category");
        var strUser = e.options[e.selectedIndex].value;

        console.log(strUser);
    }
</script>

<?php
include_once VIEW_PATH . 'common/footer.phtml';
?>
