<?php
include_once getenv("VIEW_PATH") . 'common/header.phtml';

$user = new User();
$user->findById($_GET['id']);
$isAdmin = Session::getInstance()->getUserId() == 1;

if ($user->getId() == 1 && !$isAdmin) {
    redirect_to('/admin/users');
}

?>

<form method="post">
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Are you sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger" formaction="<?= '/user/delete' ?>">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <input type="hidden" name="user[id]" value="<?= $user->getId() ?>">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="firstNameInput">First name</label>
            <input type="text" class="form-control" name="user[first_name]" value="<?= $user->getFirstName() ?>">
        </div>
        <div class="form-group col-md-6">
            <label for="LastNameInput">Last name</label>
            <input type="text" class="form-control" name="user[last_name]" value="<?= $user->getLastName() ?>">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputEmail4">Email</label>
            <input type="email" class="form-control" name="user[email]" value="<?= $user->getEmail() ?>">
        </div>
        <div class="form-group col-md-6">
            <label for="inputAddress">Address</label>
            <input type="text" class="form-control" name="user[address]" value="<?= $user->getAddress() ?>">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputState">Gender</label>
            <select name="user[gender]" class="form-control">
                <option <?= $user->getGender() == 'male' ? 'selected' : '' ?>>male</option>
                <option <?= $user->getGender() == 'female' ? 'selected' : '' ?>>female</option>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="birthdayInput">Birthday</label>
            <input type="text" class="form-control" name="user[birthday]" id="birthday" value="<?= $user->getBirthday() ?>">
        </div>
    </div>


    <button type="submit" class="btn btn-primary" formaction="<?= '/user/update' ?>">Update</button>
    <?php if ($user->getId() != 1): ?>
        <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModalCenter">Delete</button>
    <?php endif; ?>
    <button type="submit" class="btn btn-warning float-right" formaction="<?= $_SERVER['HTTP_REFERER'] ?>">Back</button>

    <?php if ($lastChange): ?>
        <p class="text-center">Last changes: <?=$lastChange?></p>
    <?php endif; ?>
</form>

<script>
    $("#birthday").flatpickr({
        dateFormat: "Y-m-d",
    });
</script>

<?php
include_once getenv("VIEW_PATH") . 'common/footer.phtml';
?>
