<?php
include_once getenv("VIEW_PATH") . 'common/header.phtml';

$availabilities = Availability::getAllAvailabilityById($id);
$colors = [];
?>

<div class="text-center mb-3">
    <img src="<?= '/image?product=' . $product->getImage() ?>" class="img-fluid" style="width: 500px" alt="Responsive image">
</div>

<form action="<?= '/basket/add' ?>" method="post">
    <div class="form-row d-flex justify-content-center">
        <div class="card bg-secondary w-50">
            <input type="hidden" name="product[product_id]" value="<?= $product->getId() ?? '' ?>">
            <div class="card-header" style="color: white;">
                <?=$product->getName() ?? ''?>
                <span class="badge badge-pill badge-warning float-right">
                <?=$product->getCost() ?? ''?><?=' ' . (Website::getInstance())->getCurrency()?>
            </span>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <span class="badge badge-dark">Brand:</span>
                    <span class="float-right"><?= $product->getBrand() ?? '' ?></span>
                </li>
                <li class="list-group-item">
                    <span class="badge badge-dark">Cost:</span>
                    <span class="float-right"><?= $product->getCost() ?? '' ?></span>
                </li>
                <li class="list-group-item">
                    <span class="badge badge-dark">Category:</span>
                    <span class="float-right"><?= $product->getCategory() ?? '' ?></span>
                </li>
                <li class="list-group-item">
                    <span class="badge badge-dark">Subcategory:</span>
                    <span class="float-right"><?= $product->getSubcategory() ?? '' ?></span>
                </li>
                <li class="list-group-item">
                    <span class="badge badge-dark">Group:</span>
                    <span class="float-right"><?= $product->getTargetGroup() ?? '' ?></span>
                </li>
                <li class="list-group-item">
                    <span class="badge badge-dark">Color:</span>
                    <div class="btn-group btn-group-toggle float-right" id="colorRadio" data-toggle="buttons">
                        <?php foreach ($availabilities as $availability): ?>
                            <?php if ($availability['amount'] != 0 && !in_array($availability['color'], $colors)): ?>
                                <label class="btn btn-secondary">
                                    <input type="radio" name="product[color]" value="<?=$availability['color'];?>" autocomplete="off" checked> <?=$availability['color'];?>
                                </label>
                                <?php $colors[] = $availability['color'];
                            endif; ?>
                        <?php endforeach; ?>
                    </div>
                </li>
                <li class="list-group-item">
                    <span class="badge badge-dark">Size:</span>
                    <div class="btn-group btn-group-toggle float-right" id="sizeRadio" data-toggle="buttons"></div>
                </li>
            </ul>
        </div>
</form>

<script>

    $( "#colorRadio" ).on( "click", function() {
        setTimeout(function(){
            addSizes( $( "input:checked" ).val());
        }, 1);
    });

    function addSizes(value) {
        let sizes = [];

        <?php foreach ($availabilities as $availability) : ?>
        if ('<?=$availability['color']?>' === value) {
            sizes.push(['<?=$availability['size']?>']);
        }
        <?php endforeach; ?>

        $('#sizeRadio')
            .find('label')
            .remove();

        sizes.forEach(function (value) {
            $('#sizeRadio')
                .append(
                    '<label class="btn btn-secondary">\n' +
                    '   <input type="radio" name="product[size]" value=\'' + value + '\' autocomplete="off">' + value + '\n' +
                    '</label>'
                );
        });
    }
</script>

<?php
include_once getenv("VIEW_PATH") . 'common/footer.phtml';
?>
