<?php
include_once getenv("VIEW_PATH") . 'common/header.phtml';

$productObject = new Product();
$id = '';

?>

<style>
    .card a {
        color: black;
        text-decoration: none !important;
    }
</style>

<?php foreach ($products as $product): ?>
    <?php $id = $product['product_id'] ?? $product['id'] ?>
    <?php $productObject->findById($id) ?>
    <div class="card" style="width: 18rem; display: inline-block; margin: 5px;">
        <a href="<?= '/product/show?id=' . $productObject->getId() ?>">
            <div style="width: 100%; height: 12vw;">
                <img src="<?= '/image?product=' . $productObject->getImage()?>" class="card-img-top" alt="...">
            </div>
            <div class="card-body text-center">
                <h5 class="card-title"><?=$productObject->getName()?>
                    <?php if ($productObject->isNew()): ?>
                        <span class="badge badge-warning">New</span>
                    <?php endif; ?>
                </h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </a>
    </div>
<?php endforeach; ?>

<?php
include_once  getenv("VIEW_PATH") . 'common/footer.phtml';
?>
