        </div>

<!--        <footer class="page-footer font-small fixed-bottom bg-dark">-->
<!--            <div class="footer-copyright text-center py-3 text-muted">© 2019 Copyright:-->
<!--                <a class="text-light" href="https://github.com/ilitygergo"> Gergő Ility</a>-->
<!--            </div>-->
<!--        </footer>-->

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>
