<?php

$session = Session::getInstance();

?>

<!DOCTYPE html>
    <html>
        <head>
            <meta name="description" content="<?= $meta ?? 'Meta data' ?>" />
            <title><?= $page_title ?? 'Page title' ?></title>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <link rel="stylesheet" href="<?= PUBLIC_PATH . 'css/style.css' ?>" />
        </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="<?= '/' ?>">Retail Shop</a>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Mens
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Footwear</a>
                                <a class="dropdown-item" href="#">Clothing</a>
                                <a class="dropdown-item" href="#">Accessories</a>
                                <a class="dropdown-item" href="#">Sale items</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Womens
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Footwear</a>
                                <a class="dropdown-item" href="#">Clothing</a>
                                <a class="dropdown-item" href="#">Accessories</a>
                                <a class="dropdown-item" href="#">Sale Items</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Categories
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Kids</a>
                                <a class="dropdown-item" href="#">New Arrivals</a>
                                <a class="dropdown-item" href="#">Nike</a>
                                <a class="dropdown-item" href="#">Jordan</a>
                                <a class="dropdown-item" href="#">adidas</a>
                            </div>
                        </li>
                        <li>
                            <form class="form-inline my-2 my-lg-0">
                                <input class="form-control mr-sm-2" type="search" placeholder="Search for products" aria-label="Search">
                                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
                            </form>
                        </li>
                    </ul>

                    <?php if (!$session->isLoggedIn()): ?>
                        <button class="btn btn-secondary my-2 my-sm-0" data-toggle="modal" data-target="#login">Log in</button>
                        <form action="<?= '/register' ?>">
                            <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Sign up</button>
                        </form>
                    <?php else: ?>
                        <form action="<?= '/index/logout' ?>" method="post">
                            <button class="btn btn-danger my-2 my-sm-0" data-toggle="modal">Log out</button>
                        </form>
                    <?php endif; ?>
                </div>
            </nav>
        </header>

        <div class="container" style="margin-top: 50px;">

        <div id="login" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Login to your account</h5>
                    </div>
                    <div class="modal-body">
                        <form action="<?= '/index/login' ?>" method="post">
                            <div class="form-group">
                                <label for="emailInput">Email address</label>
                                <input type="email" name="user[email]" class="form-control" placeholder="Enter email" required>
                            </div>
                            <div class="form-group">
                                <label for="passwordInput">Password</label>
                                <input type="password" name="user[password]" class="form-control" placeholder="Password" required>
                            </div>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </form>

                        <a href="<?= '/register' ?>">New around here? Sign up</a><br>
                        <a href="#">Forgot password?</a>
                    </div>
                </div>
            </div>
        </div>
