<?php

$session = Session::getInstance();

?>

<!DOCTYPE html>
    <html>
        <head>
            <meta name="description"/>
            <title>Retail shop</title>
            <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
            <link rel="stylesheet" href="/resources/demos/style.css">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <link rel="stylesheet" href="<?= PUBLIC_PATH . 'css/style.css' ?>" />
            <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
            <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        </head>

    <body style="height: 100%; min-height: 100%;">
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="<?= '/' ?>">Retail Shop</a>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Mens
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="<?= '/selection/search?c=Footwear&g=Male' ?>">Footwear</a>
                                <a class="dropdown-item" href="<?= '/selection/search?c=Clothing&g=Male' ?>">Clothing</a>
                                <a class="dropdown-item" href="<?= '/selection/search?c=Accessories&g=Male' ?>">Accessories</a>
                                <a class="dropdown-item" href="<?= '/selection/search?g=Male&sale=TRUE' ?>">Sale items</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Womens
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="<?= '/selection/search?c=Footwear&g=Female' ?>">Footwear</a>
                                <a class="dropdown-item" href="<?= '/selection/search?c=Clothing&g=Female' ?>">Clothing</a>
                                <a class="dropdown-item" href="<?= '/selection/search?c=Accessories&g=Female' ?>">Accessories</a>
                                <a class="dropdown-item" href="<?= '/selection/search?g=Female&sale=TRUE' ?>">Sale Items</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Categories
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="<?= '/selection/search?g=Kids' ?>">Kids</a>
                                <a class="dropdown-item" href="<?= '/selection/search?new=TRUE' ?>">New Arrivals</a>
                                <a class="dropdown-item" href="<?= '/selection/search?b=Nike' ?>">Nike</a>
                                <a class="dropdown-item" href="<?= '/selection/search?b=Jordan' ?>">Jordan</a>
                                <a class="dropdown-item" href="<?= '/selection/search?b=adidas' ?>">adidas</a>
                            </div>
                        </li>
                        <li>
                            <form action="<?= '/index/search?'?>" method="post" class="form-inline my-2 my-lg-0">
                                <input value="" name="searchInput" class="form-control mr-sm-2" type="search" placeholder="Search for products" aria-label="Search">
                                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit" style="margin-right: 5px; margin-left: 5px">Search</button>
                            </form>
                        </li>
                        <?php if ((Website::getInstance())->getId() == $session->getUserId()): ?>
                            <li>
                                <form action="<?= '/admin/users' ?>" method="post" style="margin-right: 5px; margin-left: 5px">
                                    <button class="btn btn-outline-info my-2 my-sm-0" data-toggle="modal">Manage Users</button>
                                </form>
                            </li>
                            <li>
                                <form action="<?= '/admin/orders' ?>" method="post" style="margin-right: 5px; margin-left: 5px">
                                    <button class="btn btn-outline-info my-2 my-sm-0" data-toggle="modal">Manage Orders</button>
                                </form>
                            </li>
                            <li>
                                <form action="<?= '/admin/products' ?>" method="post" style="margin-right: 5px; margin-left: 5px">
                                    <button class="btn btn-outline-info my-2 my-sm-0" data-toggle="modal">Manage Products</button>
                                </form>
                            </li>
                        <?php endif; ?>
                    </ul>

                    <?php if (!$session->isLoggedIn()): ?>
                        <button class="btn btn-secondary my-2 my-sm-0" data-toggle="modal" data-target="#login">Log in</button>
                        <form action="<?= '/register' ?>" style="margin-right: 5px; margin-left: 5px">
                            <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Sign up</button>
                        </form>
                    <?php else: ?>
                        <form action="<?= '/user/profile?id=' . Session::getInstance()->getUserId() ?>" method="post" style="margin-right: 5px; margin-left: 5px">
                            <button class="btn btn-outline-info my-2 my-sm-0" data-toggle="modal">Profile</button>
                        </form>
                        <form action="<?= '/index/logout' ?>" method="post" style="margin-right: 5px; margin-left: 5px">
                            <button class="btn btn-danger my-2 my-sm-0" data-toggle="modal">Log out</button>
                        </form>
                    <?php endif; ?>
                </div>
            </nav>
        </header>

        <div class="container" style="margin-top: 50px;">

        <div id="login" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Login to your account</h5>
                    </div>
                    <div class="modal-body">
                        <form action="<?= '/index/login' ?>" method="post">
                            <div class="form-group">
                                <label for="emailInput">Email address</label>
                                <input type="email" name="user[email]" class="form-control" placeholder="Enter email" required>
                            </div>
                            <div class="form-group">
                                <label for="passwordInput">Password</label>
                                <input type="password" name="user[password]" class="form-control" placeholder="Password" required>
                            </div>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </form>

                        <a href="<?= '/register' ?>">New around here? Sign up</a><br>
                        <a href="#">Forgot password?</a>
                    </div>
                </div>
            </div>
        </div>
