<?php
include_once VIEW_PATH . 'common/header.phtml';

$basketElements = Order::getAllOrdersByUserId(Session::getInstance()->getUserId(), 'basket');

?>

<h1>Basket:</h1>

<ul class="list-group">
    <?php foreach ($basketElements as $basket): ?>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <?= $basket['availability_id'] ?>
            <?= var_export(Availability::getAllAvailabilityById($basket['availability_id'])) ?>
            <span class="badge badge-primary badge-pill">14</span>
        </li>
    <?php endforeach; ?>
</ul>

<?php
include_once  VIEW_PATH . 'common/footer.phtml';
?>
