<?php
include_once getenv("VIEW_PATH") . 'common/header.phtml';
?>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="<?= '/image?id=a.jpg' ?>" style="height: 550px" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="<?= '/image?id=b.jpg' ?>" style="height: 550px" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="<?= '/image?id=c.jpg' ?>" style="height: 550px" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<?php
include_once  getenv("VIEW_PATH") . 'common/footer.phtml';
?>
