<?php
$page_title = 'Register Page';

include_once 'common/header.phtml';

if (isPostRequest() && isset($_POST['user'])) {
    $user = UserModel::getInstance();
    $user->init($_POST['user']);
    $user->setPassword($_POST['user']['password']);
    $user->create();

    redirect_to('/');
}

if (!empty($errors = \Model::$errors)) {
    foreach ($errors as $error) { ?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
        <?php
    }
}
?>

<div class="card">
    <div class="card-header">
        <h1>Register now:</h1>
    </div>
    <div class="card-body">
        <form action="<?= '/register' ?>" method="post">
            <div class="form-group">
                <label for="firstNameInput">First Name</label>
                <input type="text" name="user[first_name]" class="form-control" placeholder="First name" required>
            </div>
            <div class="form-group">
                <label for="lastNameInput">Last Name</label>
                <input type="text" name="user[last_name]" class="form-control" placeholder="Last name" required>
            </div>
            <div class="form-group">
                <label for="emailInput">Email address</label>
                <input type="email" name="user[email]" class="form-control" placeholder="Enter email" required>
                <small class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                <label for="passwordInput">Password</label>
                <input type="password" name="user[password]" class="form-control" placeholder="Password" required>
                <small class="form-text text-muted">Password must contain: 8 characters (1 lowercase, 1 uppercase), 1 number</small>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</div>

<?php
include_once 'common/footer.phtml';
?>
