<?php
include_once getenv("VIEW_PATH") . 'common/header.phtml';

use App\Models\Pagination;
use App\Models\Product;
use App\Models\Website;

$pagination = new Pagination($_GET['page'] ?? 1, 10, Product::getAll([], TRUE));
$products = Product::getAll([], FALSE, $pagination->per_page, $pagination->offset());
$website = Website::getInstance();
?>

<ul class="list-group">
    <div class="form-row">
        <div class="form-group col-md-6">
            <a href="<?= '/admin/products?id=create' ?>" class="btn btn-primary">Create Product</a>
        </div>
        
        <div class="col-md-12">
            <?= $pagination->navigationButtons(); ?>
        </div>

    </div>
    <?php foreach ($products as $product): ?>
        <a href="<?= '/admin/products?id=' . $product['id'] ?>" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><?= $product['name'] . ' (' . $product['brand'] . ')'?></h5>
                <small><?= $product['cost'] . ' ' . $website->getCurrency()?></small>
            </div>
            <small><?= $product['category'] . ' - ' . $product['subcategory'] ?></small>
        </a>
        <?php endforeach; ?>
</ul>

<?php
include_once getenv("VIEW_PATH") . 'common/footer.phtml';
?>
