<?php
include_once getenv("VIEW_PATH") . 'common/header.phtml';

$pagination = new Pagination($_GET['page'] ?? 1, 10, User::countAll());
$users = User::getAll($pagination->per_page, $pagination->offset());
?>

<?= $pagination->navigationButtons(); ?>

<ul class="list-group">
    <?php foreach ($users as $user): ?>
        <?php $userObject = new User($user); ?>
        <?php if ($user['id'] == (Website::getInstance())->getId()): ?>
            <a href="<?= '/admin/users?id=' . $user['id'] ?>" class="list-group-item list-group-item-action flex-column align-items-start active">
            <small>Admin</small>
        <?php else: ?>
            <a href="<?= '/admin/users?id=' . $user['id'] ?>" class="list-group-item list-group-item-action flex-column align-items-start">
        <?php endif; ?>
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><?= $user['first_name'] . ' ' . $user['last_name'] . ' (' . $userObject->getAge() . ')'?></h5>
                    <small><?= $user['email'] ?></small>
                </div>
                <small><?= $user['address'] ?></small>
            </a>
    <?php endforeach; ?>
</ul>

<?php
include_once getenv("VIEW_PATH") . 'common/footer.phtml';
?>
